#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "The Dry Dock"
# OpenGraph / Twitter Card metadata
description = "The Becoming Of Self"
author = "Jerad"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "A Journey In The Becoming Of Self.<br>1. Life is a gift<br>2. Be true to the self<br>3. Participate in reality"

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "Re-Designed by Jerad Acosta - [JeradXYZ](https://jerad.xyz) - in 2022. Record & process of discovery, becoming, and identity"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = true

# Main Sections
#mainSections = ["blog"]
mainSections = ["poems"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Tahiti, French Polynesia"
phone = ["87 70 10 15"]
email = []

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = false
label = "Capital-M Me"
link = ""

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "A Wise Cat Once Said:"
content = "***'If you don't know where you are going,<br> any road will get you there.'*** <br><br> Empathize in one hero's journey to self; their commitment to **B**eing; and their pursuit of **participation**."
button = "Try The Mask On Now"
button_link = "/start/"

############################# social site ########################
[[social]]
title = "The Dry Dock"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "The Dry Dock Tweet"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "https://twitter.com/thedrydockxyz"

[[social]]
title = "Dry Dock-In"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "Dry Dock-Pin"
icon = "lab la-pinterest" # https://icons8.com/line-awesome
link = "#!"
