#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Dry Docking"
# OpenGraph / Twitter Card metadata
description = "The Becoming Of Self"
author = "Jerad"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own

# footer information
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = true

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "Tahiti, French Polynesia"
phone = ["87 70 10 15"]
email = []

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Capital-M Me"
link = "https://gethugothemes.com/products/andromeda/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Check Out *A* Way"
content =   "**A Wise Cat Once Said:** *'If you don't know where you are going, any road will get you there.'*<br>Empathize in one hero's journey to self; their commitment to **B**eing; and their pursuit of participation."
button = "Try Their Mask On Now"
button_link = "/blog/"

############################# social site ########################
[[social]]
title = "Dry Docking"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "Dry Docking Tweet"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "Dry Dock-In"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "Dry Dock-Pin"
icon = "lab la-pinterest" # https://icons8.com/line-awesome
link = "#!"
